Repository 0shade0/Java-Projekt, pull requests merged in 2021-06, with the labels that each got.

#23 Playfair
  kriptografija/src/main/java/pmf/math/kalkulatori/PlayfairKalkulator.form
  kriptografija/src/main/java/pmf/math/kalkulatori/PlayfairKalkulator.java
  kriptografija/src/main/java/pmf/math/konstante/OpisiKalkulatora.java
  kriptografija/src/main/java/pmf/math/konstante/PlayfairAbecede.java
  kriptografija/src/main/java/pmf/math/konstante/UputeKalkulatora.java
  kriptografija/src/main/java/pmf/math/kriptosustavi/PlayfairKriptosustav.java
  kriptografija/src/main/java/pmf/math/router/Opis.form
  kriptografija/src/main/java/pmf/math/router/Opis.java
  kriptografija/src/main/java/pmf/math/router/Router.form
  kriptografija/src/main/java/pmf/math/router/Router.java
  kriptografija/src/test/java/pmf/math/kriptosustavi/PlayfairKriptosustavTest.java
Labels: computation

#26 Opca supstitucijska
  kriptografija/src/main/java/pmf/math/algoritmi/Abeceda.java
  kriptografija/src/main/java/pmf/math/kalkulatori/CezarKalkulator.form
  kriptografija/src/main/java/pmf/math/kalkulatori/CezarKalkulator.java
  kriptografija/src/main/java/pmf/math/kalkulatori/SupstitucijskaKalkulator.form
  kriptografija/src/main/java/pmf/math/kalkulatori/SupstitucijskaKalkulator.java
  kriptografija/src/main/java/pmf/math/konstante/OpisiKalkulatora.java
  kriptografija/src/main/java/pmf/math/konstante/UputeKalkulatora.java
  kriptografija/src/main/java/pmf/math/kriptosustavi/CezarKljucnaRijecKriptosustav.java
  kriptografija/src/main/java/pmf/math/kriptosustavi/CezarKriptosustav.java
  kriptografija/src/main/java/pmf/math/kriptosustavi/SupstitucijskaKriptosustav.java
  kriptografija/src/main/java/pmf/math/obradaunosa/ObradaUnosa.java
  kriptografija/src/main/java/pmf/math/obradaunosa/ObradaUnosaCezar.java
  kriptografija/src/main/java/pmf/math/obradaunosa/ObradaUnosaCezarKljucnaRijec.java
  kriptografija/src/main/java/pmf/math/router/Router.form
  kriptografija/src/main/java/pmf/math/router/Router.java
  kriptografija/src/test/java/pmf/math/kriptosustavi/CezarKljucnaRijecKriptosustavTest.java
  kriptografija/src/test/java/pmf/math/kriptosustavi/CezarKriptosustavTest.java
  kriptografija/src/test/java/pmf/math/kriptosustavi/SupstitucijskaKriptosustavTest.java
  kriptografija/src/test/java/pmf/math/obradaunosa/ObradaUnosaCezarKljucnaRijecTest.java
  kriptografija/src/test/java/pmf/math/obradaunosa/ObradaUnosaCezarTest.java
  kriptografija/src/test/java/pmf/math/obradaunosa/ObradaUnosaTest.java
Labels: computation

#27 Gotov Hillov kriptosustav.
  kriptografija/src/main/java/pmf/math/algoritmi/Matrica.java
  kriptografija/src/main/java/pmf/math/algoritmi/Vektor.java
  kriptografija/src/main/java/pmf/math/kalkulatori/HillKalkulator.form
  kriptografija/src/main/java/pmf/math/kalkulatori/HillKalkulator.java
  kriptografija/src/main/java/pmf/math/kalkulatori/PlayfairKalkulator.java
  kriptografija/src/main/java/pmf/math/konstante/HillMatrice.java
  kriptografija/src/main/java/pmf/math/konstante/OpisiKalkulatora.java
  kriptografija/src/main/java/pmf/math/konstante/UputeKalkulatora.java
  kriptografija/src/main/java/pmf/math/kriptosustavi/HillKriptosustav.java
  kriptografija/src/main/java/pmf/math/router/Opis.form
  kriptografija/src/main/java/pmf/math/router/Opis.java
  kriptografija/src/main/java/pmf/math/router/Router.java
  kriptografija/src/test/java/pmf/math/algoritmi/MatricaTest.java
  kriptografija/src/test/java/pmf/math/algoritmi/VektorTest.java
  kriptografija/src/test/java/pmf/math/kriptosustavi/HillKriptosustavTest.java
Labels: computation

#29 Uvedena baza podataka i primjer korištenja za Playfair Kriptosustav
  .gitignore
  kriptografija/pom.xml
  kriptografija/src/main/java/pmf/math/algoritmi/VrijemeDatum.java
  kriptografija/src/main/java/pmf/math/baza/BazaPodataka.java
  kriptografija/src/main/java/pmf/math/baza/dao/HillDAO.java
  kriptografija/src/main/java/pmf/math/baza/dao/PlayfairDAO.java
  kriptografija/src/main/java/pmf/math/baza/tablice/HillFavoriti.java
  kriptografija/src/main/java/pmf/math/baza/tablice/PlayfairFavoriti.java
  kriptografija/src/main/java/pmf/math/kalkulatori/HillKalkulator.form
  kriptografija/src/main/java/pmf/math/kalkulatori/HillKalkulator.java
  kriptografija/src/main/java/pmf/math/kalkulatori/PlayfairKalkulator.form
  kriptografija/src/main/java/pmf/math/kalkulatori/PlayfairKalkulator.java
  kriptografija/src/main/java/pmf/math/router/Router.java
Labels: dodatak

#35 Vigenereov kriptosustav
  kriptografija/src/main/java/pmf/math/MainClass.java
  kriptografija/src/main/java/pmf/math/algoritmi/Abeceda.java
  kriptografija/src/main/java/pmf/math/baza/dao/HillDAO.java
  kriptografija/src/main/java/pmf/math/baza/dao/PlayfairDAO.java
  kriptografija/src/main/java/pmf/math/baza/dao/VigenereDAO.java
  kriptografija/src/main/java/pmf/math/baza/tablice/HillPovijest.java
  kriptografija/src/main/java/pmf/math/baza/tablice/PlayfairPovijest.java
  kriptografija/src/main/java/pmf/math/baza/tablice/VigenerePovijest.java
  kriptografija/src/main/java/pmf/math/kalkulatori/HillKalkulator.form
  kriptografija/src/main/java/pmf/math/kalkulatori/HillKalkulator.java
  kriptografija/src/main/java/pmf/math/kalkulatori/PlayfairKalkulator.form
  kriptografija/src/main/java/pmf/math/kalkulatori/PlayfairKalkulator.java
  kriptografija/src/main/java/pmf/math/kalkulatori/VigenereKalkulator.form
  kriptografija/src/main/java/pmf/math/kalkulatori/VigenereKalkulator.java
  kriptografija/src/main/java/pmf/math/konstante/OpisiKalkulatora.java
  kriptografija/src/main/java/pmf/math/konstante/UputeKalkulatora.java
  kriptografija/src/main/java/pmf/math/kriptosustavi/VigenereKriptosustav.java
  kriptografija/src/main/java/pmf/math/router/Router.java
  kriptografija/src/test/java/pmf/math/algoritmi/AbecedaTest.java
  kriptografija/src/test/java/pmf/math/kriptosustavi/VigenereKriptosustavTest.java
  kriptografija/src/test/java/pmf/math/unit/MainClassTest.java
Labels: kriptografija

#37 Analiza teksta
  kriptografija/src/main/java/pmf/math/algoritmi/Abeceda.java
  kriptografija/src/main/java/pmf/math/algoritmi/AnalizaTeksta.java
  kriptografija/src/main/java/pmf/math/kalkulatori/AnalizaTekstaKalkulator.form
  kriptografija/src/main/java/pmf/math/kalkulatori/AnalizaTekstaKalkulator.java
  kriptografija/src/main/java/pmf/math/kalkulatori/HillKalkulator.java
  kriptografija/src/main/java/pmf/math/kalkulatori/PlayfairKalkulator.java
  kriptografija/src/main/java/pmf/math/kalkulatori/VigenereKalkulator.java
  kriptografija/src/main/java/pmf/math/konstante/DuljineTeksta.java
  kriptografija/src/main/java/pmf/math/konstante/ImenaKalkulatora.java
  kriptografija/src/main/java/pmf/math/konstante/OpisiKalkulatora.java
  kriptografija/src/main/java/pmf/math/konstante/UputeKalkulatora.java
  kriptografija/src/main/java/pmf/math/konstante/VelicineFontova.java
  kriptografija/src/main/java/pmf/math/router/Konzola.form
  kriptografija/src/main/java/pmf/math/router/Konzola.java
  kriptografija/src/main/java/pmf/math/router/Opis.form
  kriptografija/src/main/java/pmf/math/router/Opis.java
  kriptografija/src/main/java/pmf/math/router/Router.form
  kriptografija/src/main/java/pmf/math/router/Router.java
  kriptografija/src/main/java/pmf/math/ui/MainWindow.form
  kriptografija/src/main/java/pmf/math/ui/MainWindow.java
  kriptografija/src/test/java/pmf/math/algoritmi/AnalizaTekstaTest.java
Labels: dodatak, korisničko sučelje

#39 Popravci el gamal
  kriptografija/src/main/java/pmf/math/baza/dao/ElGamalDAO.java
  kriptografija/src/main/java/pmf/math/baza/tablice/ElGamalPovijest.java
  kriptografija/src/main/java/pmf/math/kalkulatori/ElGamalKalkulator.form
  kriptografija/src/main/java/pmf/math/kalkulatori/ElGamalKalkulator.java
  kriptografija/src/main/java/pmf/math/kalkulatori/PlayfairKalkulator.java
  kriptografija/src/main/java/pmf/math/kalkulatori/RSAKalkulator.java
  kriptografija/src/main/java/pmf/math/konstante/OpisiKalkulatora.java
  kriptografija/src/main/java/pmf/math/konstante/UputeKalkulatora.java
  kriptografija/src/main/java/pmf/math/kriptosustavi/ElGamalKriptosustav.java
  kriptografija/src/test/java/pmf/math/kriptosustavi/ElGamalKriptosustavTest.java
Labels: kriptografija

#41 Grafovi performansi
  kriptografija/pom.xml
  kriptografija/src/main/java/pmf/math/baza/dao/TekstGrafDAO.java
  kriptografija/src/main/java/pmf/math/baza/tablice/TekstGrafovi.java
  kriptografija/src/main/java/pmf/math/filteri/PlayfairFilter.java
  kriptografija/src/main/java/pmf/math/kalkulatori/PlayfairKalkulator.java
  kriptografija/src/main/java/pmf/math/konstante/DuljineTeksta.java
  kriptografija/src/main/java/pmf/math/kriptosustavi/HillKriptosustav.java
  kriptografija/src/main/java/pmf/math/kriptosustavi/PlayfairKriptosustav.java
  kriptografija/src/main/java/pmf/math/pomagala/GeneratorTeksta.java
  kriptografija/src/main/java/pmf/math/pomagala/Stoperica.java
  kriptografija/src/main/java/pmf/math/pomagala/StringInteger.java
  kriptografija/src/main/java/pmf/math/pomagala/VrijemeDatum.java
  kriptografija/src/main/java/pmf/math/router/Opis.form
  kriptografija/src/main/java/pmf/math/router/Opis.java
  kriptografija/src/main/java/pmf/math/router/Router.form
  kriptografija/src/main/java/pmf/math/router/Router.java
  kriptografija/src/test/java/pmf/math/integration/ITMainClass.java
Labels: korisničko sučelje, kriptografija

#43 Popravci RSA
  kriptografija/src/main/java/pmf/math/algoritmi/TeorijaBrojeva.java
  kriptografija/src/main/java/pmf/math/baza/dao/RSADAO.java
  kriptografija/src/main/java/pmf/math/baza/tablice/RSAPovijest.java
  kriptografija/src/main/java/pmf/math/kalkulatori/ElGamalKalkulator.form
  kriptografija/src/main/java/pmf/math/kalkulatori/ElGamalKalkulator.java
  kriptografija/src/main/java/pmf/math/kalkulatori/RSAKalkulator.form
  kriptografija/src/main/java/pmf/math/kalkulatori/RSAKalkulator.java
  kriptografija/src/main/java/pmf/math/konstante/OpisiKalkulatora.java
  kriptografija/src/main/java/pmf/math/konstante/UputeKalkulatora.java
  kriptografija/src/main/java/pmf/math/kriptosustavi/RSAKriptosustav.java
  kriptografija/src/main/java/pmf/math/obradaunosa/ObradaUnosaRSA.java
Labels: kriptografija
